// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxvS1u7Rl_8a5s08Zp-_2ehQ4NCJmAPc',
    appId: '1:67930967224:web:e4da2cb661509dcbd7784d',
    messagingSenderId: '67930967224',
    projectId: 'exercise9-d6907',
    authDomain: 'exercise9-d6907.firebaseapp.com',
    storageBucket: 'exercise9-d6907.firebasestorage.app',
    measurementId: 'G-M46V9FRV2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFJVtUwzVfen7MGsLURq_jNwKQUgu1W0',
    appId: '1:67930967224:android:4e4e8bdb96a8c2fad7784d',
    messagingSenderId: '67930967224',
    projectId: 'exercise9-d6907',
    storageBucket: 'exercise9-d6907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJM1_2Se2s99dNh3GGLmzX4W_zb_pT2H0',
    appId: '1:67930967224:ios:1a8608ac67effe7bd7784d',
    messagingSenderId: '67930967224',
    projectId: 'exercise9-d6907',
    storageBucket: 'exercise9-d6907.firebasestorage.app',
    iosBundleId: 'com.example.exercise9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJM1_2Se2s99dNh3GGLmzX4W_zb_pT2H0',
    appId: '1:67930967224:ios:1a8608ac67effe7bd7784d',
    messagingSenderId: '67930967224',
    projectId: 'exercise9-d6907',
    storageBucket: 'exercise9-d6907.firebasestorage.app',
    iosBundleId: 'com.example.exercise9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUxvS1u7Rl_8a5s08Zp-_2ehQ4NCJmAPc',
    appId: '1:67930967224:web:acdec27db1077f1dd7784d',
    messagingSenderId: '67930967224',
    projectId: 'exercise9-d6907',
    authDomain: 'exercise9-d6907.firebaseapp.com',
    storageBucket: 'exercise9-d6907.firebasestorage.app',
    measurementId: 'G-RKQH7BJQC7',
  );
}
